CREATE TABLE IF NOT EXISTS public.albums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    title_original TEXT NOT NULL DEFAULT '',
    artists TEXT NOT NULL DEFAULT '',
    composers TEXT NOT NULL DEFAULT '',
    performers TEXT NOT NULL DEFAULT '',
    label TEXT NOT NULL DEFAULT '',
    catalog_number TEXT NOT NULL DEFAULT '',
    barcode TEXT NOT NULL DEFAULT '',
    media_type TEXT NOT NULL DEFAULT 'CD',
    disc_count INTEGER NOT NULL DEFAULT 1 CHECK (disc_count >= 1),
    origin TEXT NOT NULL DEFAULT '不明',
    country TEXT NOT NULL DEFAULT '',
    release_year TEXT NOT NULL DEFAULT '',
    genre TEXT NOT NULL DEFAULT '',
    recording_format TEXT NOT NULL DEFAULT '',
    location TEXT NOT NULL DEFAULT '',
    purchase_date TEXT NOT NULL DEFAULT '',
    purchase_price INTEGER CHECK (purchase_price IS NULL OR purchase_price >= 0),
    rating INTEGER NOT NULL DEFAULT 0 CHECK (rating BETWEEN 0 AND 5),
    condition TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    musicbrainz_release_id TEXT NOT NULL DEFAULT '',
    cover_url TEXT NOT NULL DEFAULT '',
    cover_source TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT 'manual',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.tracks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id BIGINT NOT NULL REFERENCES public.albums(id) ON DELETE CASCADE,
    disc_number INTEGER NOT NULL DEFAULT 1 CHECK (disc_number >= 1),
    track_number TEXT NOT NULL DEFAULT '',
    title TEXT NOT NULL,
    artists TEXT NOT NULL DEFAULT '',
    performers TEXT NOT NULL DEFAULT '',
    composers TEXT NOT NULL DEFAULT '',
    duration_ms INTEGER CHECK (duration_ms IS NULL OR duration_ms >= 0),
    isrc TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_albums_barcode ON public.albums(barcode);
CREATE INDEX IF NOT EXISTS idx_albums_catalog_number ON public.albums(catalog_number);
CREATE INDEX IF NOT EXISTS idx_albums_title ON public.albums(title);
CREATE INDEX IF NOT EXISTS idx_tracks_album_order ON public.tracks(album_id, disc_number, id);

ALTER TABLE public.albums ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tracks ENABLE ROW LEVEL SECURITY;

-- 既にalbumsテーブルを作成済みの場合の安全な追加。
ALTER TABLE public.albums ADD COLUMN IF NOT EXISTS cover_url TEXT NOT NULL DEFAULT '';
ALTER TABLE public.albums ADD COLUMN IF NOT EXISTS cover_source TEXT NOT NULL DEFAULT '';
ALTER TABLE public.albums ADD COLUMN IF NOT EXISTS rating INTEGER NOT NULL DEFAULT 0 CHECK (rating BETWEEN 0 AND 5);

-- このアプリはStreamlit Secretsのservice_roleキーでアクセスします。
-- service_roleはRLSをバイパスするため、公開クライアントへ絶対に渡さないでください。
