CREATE TABLE IF NOT EXISTS public.albums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    title_original TEXT NOT NULL DEFAULT '',
    artists TEXT NOT NULL DEFAULT '',
    composers TEXT NOT NULL DEFAULT '',
    performers TEXT NOT NULL DEFAULT '',
    label TEXT NOT NULL DEFAULT '',
    catalog_number TEXT NOT NULL DEFAULT '',
    barcode TEXT NOT NULL DEFAULT '',
    media_type TEXT NOT NULL DEFAULT 'CD',
    disc_count INTEGER NOT NULL DEFAULT 1 CHECK (disc_count >= 1),
    origin TEXT NOT NULL DEFAULT '不明',
    country TEXT NOT NULL DEFAULT '',
    release_year TEXT NOT NULL DEFAULT '',
    genre TEXT NOT NULL DEFAULT '',
    recording_format TEXT NOT NULL DEFAULT '',
    location TEXT NOT NULL DEFAULT '',
    purchase_date TEXT NOT NULL DEFAULT '',
    purchase_price INTEGER CHECK (purchase_price IS NULL OR purchase_price >= 0),
    rating INTEGER NOT NULL DEFAULT 0 CHECK (rating BETWEEN 0 AND 5),
    condition TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    musicbrainz_release_id TEXT NOT NULL DEFAULT '',
    cover_url TEXT NOT NULL DEFAULT '',
    cover_source TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT 'manual',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.tracks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    album_id BIGINT NOT NULL REFERENCES public.albums(id) ON DELETE CASCADE,
    disc_number INTEGER NOT NULL DEFAULT 1 CHECK (disc_number >= 1),
    track_number TEXT NOT NULL DEFAULT '',
    title TEXT NOT NULL,
    artists TEXT NOT NULL DEFAULT '',
    performers TEXT NOT NULL DEFAULT '',
    composers TEXT NOT NULL DEFAULT '',
    duration_ms INTEGER CHECK (duration_ms IS NULL OR duration_ms >= 0),
    isrc TEXT NOT NULL DEFAULT '',
    rating INTEGER NOT NULL DEFAULT 0 CHECK (rating BETWEEN 0 AND 5)
);

CREATE INDEX IF NOT EXISTS idx_albums_barcode ON public.albums(barcode);
CREATE INDEX IF NOT EXISTS idx_albums_user_id ON public.albums(user_id);
CREATE INDEX IF NOT EXISTS idx_albums_catalog_number ON public.albums(catalog_number);
CREATE INDEX IF NOT EXISTS idx_albums_title ON public.albums(title);
CREATE INDEX IF NOT EXISTS idx_tracks_album_order ON public.tracks(album_id, disc_number, id);
CREATE INDEX IF NOT EXISTS idx_tracks_user_id ON public.tracks(user_id);

ALTER TABLE public.albums ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tracks ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.albums, public.tracks FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.albums, public.tracks TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

DROP POLICY IF EXISTS "users read own albums" ON public.albums;
DROP POLICY IF EXISTS "users insert own albums" ON public.albums;
DROP POLICY IF EXISTS "users update own albums" ON public.albums;
DROP POLICY IF EXISTS "users delete own albums" ON public.albums;
CREATE POLICY "users read own albums" ON public.albums FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = user_id);
CREATE POLICY "users insert own albums" ON public.albums FOR INSERT TO authenticated
WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY "users update own albums" ON public.albums FOR UPDATE TO authenticated
USING ((SELECT auth.uid()) = user_id) WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY "users delete own albums" ON public.albums FOR DELETE TO authenticated
USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "users read own tracks" ON public.tracks;
DROP POLICY IF EXISTS "users insert own tracks" ON public.tracks;
DROP POLICY IF EXISTS "users update own tracks" ON public.tracks;
DROP POLICY IF EXISTS "users delete own tracks" ON public.tracks;
CREATE POLICY "users read own tracks" ON public.tracks FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = user_id);
CREATE POLICY "users insert own tracks" ON public.tracks FOR INSERT TO authenticated
WITH CHECK (
  (SELECT auth.uid()) = user_id
  AND EXISTS (
    SELECT 1 FROM public.albums a
    WHERE a.id = album_id AND a.user_id = (SELECT auth.uid())
  )
);
CREATE POLICY "users update own tracks" ON public.tracks FOR UPDATE TO authenticated
USING ((SELECT auth.uid()) = user_id)
WITH CHECK (
  (SELECT auth.uid()) = user_id
  AND EXISTS (
    SELECT 1 FROM public.albums a
    WHERE a.id = album_id AND a.user_id = (SELECT auth.uid())
  )
);
CREATE POLICY "users delete own tracks" ON public.tracks FOR DELETE TO authenticated
USING ((SELECT auth.uid()) = user_id);

-- 既にalbumsテーブルを作成済みの場合の安全な追加。
ALTER TABLE public.albums ADD COLUMN IF NOT EXISTS cover_url TEXT NOT NULL DEFAULT '';
ALTER TABLE public.albums ADD COLUMN IF NOT EXISTS cover_source TEXT NOT NULL DEFAULT '';
ALTER TABLE public.albums ADD COLUMN IF NOT EXISTS rating INTEGER NOT NULL DEFAULT 0 CHECK (rating BETWEEN 0 AND 5);
ALTER TABLE public.tracks ADD COLUMN IF NOT EXISTS rating INTEGER NOT NULL DEFAULT 0 CHECK (rating BETWEEN 0 AND 5);

-- このアプリはSupabase AuthのユーザーJWTでアクセスし、RLSで本人のデータだけを許可します。
